### ISSUE TITLE
Order No. 1565611645487

### ISSUE THREAD

**Issue by carlossampol** [EthereumCommonwealth/Auditing#364] opened 2019-08-12 12:07 UTC
# Audit request
HEX.win
# Source code
https://gitlab.com/bitcoinhex/contract-staging
# Disclosure policy
I need to add you to the repo in gitlab. RichardHeartAuthor@gmail.com
# Platform
Ethereum

**Comment by yuriy77k** [comment] 2019-08-13 08:10
Duplicate of this request: https://github.com/EthereumCommonwealth/Auditing/issues/365

**Closed** 2019-08-13 08:10 UTC
Labels: duplicate, withdrawn
